# Chip is ESP32-S3 (QFN56) (revision v0.2)
# Features: WiFi, BLE, Embedded PSRAM 8MB (AP_3v3)
# Crystal is 40MHz
# Detected flash size: 8MB
# Flash type set in eFuse: quad (4 data lines)

esphome:
  platformio_options:
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: qio
    build_flags:
      - "-DCONFIG_SPIRAM_CACHE_WORKAROUND"
      - "-mfix-esp32-psram-cache-issue"

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: arduino

psram:
  mode: octal
  speed: 80MHz

sensor:
  - platform: debug
    psram:
      name: "Free PSRAM"

# binary_sensor:
#   - platform: gpio
#     pin:
#       number: GPIO0
#       mode:
#         input: true
#         pullup: true
#       inverted: true
#     name: "Boot Button"
#     id: boot_btn
#     disabled_by_default: true
#     entity_category: "diagnostic"